Migrating from CloudConfiguration to CloudEnvironment
IBM-Swift/TodoList-CouchDB pull request #37
Opened 2017-11-10 10:30 UTC by ShihabMehboob

Removed CloudConfiguration and replaced with CloudEnvironment.

2017-11-10 11:24 UTC, KyeMaloy97 commented on Sources/Server/main.swift
> -CloudFoundryDeploymentTracker(repositoryURL: "https://github.com/IBM-Swift/TodoList-CouchDB.git").track()
Didn't seem to be any equivalent in CloudEnvironment.

2017-11-10 16:41 UTC, rolivieri requested changes
We need a config folder with the corresponding files in it (e.g. mappings.json, etc.). Can you add those? As reference see:

https://github.com/IBM-Swift/CloudEnvironment (REAMDE)
https://github.com/IBM-Bluemix/get-started-swift (sample app)

2017-11-13 15:48 UTC, rolivieri commented
@ShihabMehboob Thanks for adding the config folder along with the corresponding files. A few more things to address: 1) Can you address the conflicts in the PR (you may need to rebase). 2) Have you guys tested that the application can successfully connect to the Clouding database while a) running locally, b) running as a CloudFoundry app, and c) while running as Kube app? Leveraging the CloudEnvironment library allows you to exactly do this without having to make code changes (you only need to have the files under the config folder properly configured). Let me know if there are any questions, thanks!

2017-11-14 16:56 UTC, rolivieri commented
@ShihabMehboob Just following up on the message above: https://github.com/IBM-Swift/TodoList-CouchDB/pull/37#issuecomment-343961106. If you'd like to chat and/or have any questions, feel free to reach out on slack.

2017-11-15 13:58 UTC, ShihabMehboob commented
@rolivieri I've migrated to CloudEnv and Armada with the latest commit, which makes use of a config folder for the CloudEnv setup, and a config.sh bash file which lets the user input commands and variables to set up the cluster, create the database, and populate it (the user gets to input credentials and their Cloudant URL).

2017-11-23 10:37 UTC, KyeMaloy97 commented
This PRs code changes have been merged into PR #40 and therefore is no longer needed. That PR will be merged into master, so this one can be closed.

2017-11-23 10:37 UTC, closed without merging